### ISSUE TITLE
Error updating from 9.0.1 to 9.0.2 (TYPO3 8.7.20)

### ISSUE THREAD

**Issue by rubensutter** [AKaravas/foundation_zurb_framework#6]
After installing the new version in TYPO3 8 the backend page module throws the following error:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1218547409: 
Vendor\FoundationZurbFramework\Hooks\PageLayoutView\AccordionPreviewRenderer 
must implement interface TYPO3\CMS\Backend\View\PageLayoutViewDrawItemHookInterface 
| UnexpectedValueException thrown in file 
... /typo3/sysext/backend/Classes/View/PageLayoutView.php in line 1753. 

Requested URL: ... /typo3/index.php?M=web_layout&moduleToken=--AnonymizedToken--&id= ...

In version 9.0.1 the backend page module showed all contents and worked without errors.
The Backend List module in 9.0.2 seems to work.
I deleted the caches and still get the backend page error using version 9.0.2

**Comment by AKaravas** [comment]
Hello rubensutter. Did you have any foundation content element on the page as you updated the extension? 

If yes, which ones?

**Comment by AKaravas** [comment]
fixed. Next version should be in about 10 minutes available. 
@rubensutter  Can you please confirm that it works for you now?
Try to reinstall the extension, on the extension manager

**Comment by rubensutter** [comment]
I just installed the version 9.0.3 via extension manager. 
The error is fixed, everything works perfectly fine, 
The page module shows all content elements in the backend.

Thank you!

**Comment by AKaravas** [comment]
@rubensutter Anytime. More to come!
